name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Set the output location for the SVG file
          output: dist/github-contribution-grid-snake.svg

      # Step 3: Push the generated snake to the output branch
      - name: Push Snake Animation to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
